apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-deploy
  labels:
    app: bank-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-deploy
  template:
    metadata:
      labels:
        app: bank-deploy
    spec:
      containers:
      - name: bank-deploy
        image: nimya/bank
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bank-np-service
  labels:
    app: bank-deploy
spec:
  selector:
    app: bank-deploy

  type: NodePort
  ports:
  - nodePort: 31300
    port: 8081
    targetPort: 8081
